name: Run tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        go: ['1.23.3']
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}

      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Git for private modules
        run: |
          git config --global url."https://${{ secrets.GH_TOKEN }}@github.com/".insteadOf "https://github.com/"

      - name: Get dependencies
        run: |
          # export GOPRIVATE='go.pilab.hu/'
          go env -w GOPRIVATE='go.pilab.hu/'
          go mod download

      - name: Run tests
        run: go test -v -race ./...
        env:
          GOFLAGS: -mod=readonly

    #   - name: Upload coverage
    #     uses: codecov/codecov-action@v4
    #     with:
    #       token: ${{ secrets.CODECOV_TOKEN }}
    #       fail_ci_if_error: true
